//เอาไว้กำหนดค่าคงที่ ที่จะใช้ใน action และ reducer เฉยๆ ไม่ทำก็ได้ไม่เป็นไร
export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const LOGOUT_USER = 'logout_user';
export const LOGIN_USER = 'login_user';
export const LOGIN_USER_FAIL = 'login_user_fail';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const CHECK_PASSWORD = 'check_password';
export const UPDATE_PROFILE_SUCCESS = 'update_profile_success';
export const NAME_REG_CHANGED = 'name_changed';
export const EMAIL_REG_CHANGED = 'email_reg_changed';
export const PASSWORD_REG_CHANGED = 'password_reg_changed';
export const REPASSWORD_REG_CHANGED = 'repassword_reg_changed';
export const CREATE_REG_USER = 'create_reg_user';
export const CREATE_REG_FAIL = 'create_reg_fail';
export const EMAIL_RESET_CHANGED = 'email_reset_changed';
export const EMAIL_RESET_ERR = 'email_reset_err';
export const EMAIL_RESET_SUCCESS = 'email_reset_success';
export const EMAIL_RESET_START = 'email_reset_start';
export const EMAIL_RESET_INIT = 'email_reset_init';
export const USER_SETTING_AVATAR_CHANGED_SUCCESS = 'user_setting_avatar_changed_success';
export const USER_SETTING_PASSWORD_CHANGED = 'user_setting_password_changed';
export const USER_SETTING_CONFIRM_PASSWORD_CHANGED = 'user_setting_confirm_password_changed';
export const USER_SETTING_PASSWORD_CHANGED_INIT = 'user_setting_password_changed_init';
export const USER_SETTING_PASSWORD_CHANGED_FAIL = 'user_setting_password_changed_fail';
export const USER_SETTING_PASSWORD_CHANGED_COMPLETE = 'user_setting_password_changed_complete';
export const USER_SETTING_PASSWORD_CLEAR_DATA = 'user_setting_password_clear_data';
export const USER_SETTING_USERPROFILE_INIT = 'user_setting_userprofile_init';
export const USER_SETTING_USERPROFILE_FAIL = 'user_setting_userprofile_fail';
export const USER_SETTING_LOAD_USERPROFILE_SUCCESS = 'user_setting_load_userprofile_success';
export const USER_SETTING_USERPROFILE_PREFIX_CHANGED = 'user_setting_userprofile_prefix_changed';
export const USER_SETTING_USERPROFILE_NAME_CHANGED = 'user_setting_userprofile_name_changed';
export const USER_SETTING_USERPROFILE_SURNAME_CHANGED = 'user_setting_userprofile_surname_changed';
export const USER_SETTING_USERPROFILE_TEL_CHANGED = 'user_setting_userprofile_tel_changed';
export const USER_SETTING_USERPROFILE_STREET_CHANGED = 'user_setting_userprofile_street_changed';
export const USER_SETTING_USERPROFILE_SAVEPROFILE_SUCCESS = 'user_setting_userprofile_saveprofile_success';
export const USER_SETTING_USERPROFILE_ADD_INIT = 'user_setting_userprofile_add_init';
export const USER_SETTING_USERPROFILE_EDIT_INIT = 'user_setting_userprofile_edit_init';
export const USER_SETTING_USERPROFILE_EDITPROFILE_SUCCESS = 'user_setting_userprofile_editprofile_success';
export const USER_SETTING_USERPROFILE_EDITPROFILE_FAIL = 'user_setting_userprofile_editprofile_fail';
export const USER_SETTING_USERPROFILE_PROVINCE_CHANGED = 'user_setting_userprofile_province_changed';
export const USER_SETTING_USERPROFILE_AMPHOE_CHANGED = 'user_setting_userprofile_amphoe_changed';
export const USER_SETTING_USERPROFILE_ZIPCODE_CHANGED = 'user_setting_userprofile_zipcode_changed';
export const USER_SETTING_ABOUT_INIT = 'user_setting_about_init';//User About
export const USER_SETTING_ABOUT_SUCCESS = 'user_setting_about_success';//User About
export const USER_SETTING_ABOUT_FAIL = 'user_about_fail';//User About

export const JOB_LOADING_INIT = 'job_loading_init';//Job Screen
export const JOB_LOADING_SUCCESS = 'job_loading_success';//Job Screen
export const JOB_LOADING_FAIL = 'job_loading_fail';//Job Screen
export const JOB_SET_SELECTED_INDEX = 'job_set_selected_index';//Job Screen

export const JOB_SELECTED_INIT = 'job_selected_init';//Job Detail
export const JOB_SELECTED = 'job_selected';//Job Detail
export const JOB_SELECTED_FAIL = 'job_selected_fail';//Job Detail
export const JOB_CANCEL_INIT = 'job_cancel_init';//Job Detail
export const JOB_CANCEL_SUCCESS = 'job_cancel_success';//Job Detail
export const JOB_CANCEL_FAIL = 'job_cancel_fail';//Job Detail
export const JOB_CONFIRM_INIT = 'job_confirm_init';//Job Detail
export const JOB_CONFIRM_SUCCESS = 'job_confirm_success';//Job Detail
export const JOB_CONFIRM_FAIL = 'job_confirm_fail';//Job Detail 
export const JOB_DETAIL_RESET_LOADING = 'job_detail_reset_loading';//Job Detail